trigger:
  - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    pythonVersion: ['3.9', '3.11']  # No hyphen here in variable name

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'  # Directly use $(pythonVersion)
      addToPath: true
    displayName: 'Set up Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install -e .[ci]
    displayName: 'Install Python dependencies'

  - script: |
      pre-commit run --all-files
    displayName: 'Analyze all pre-commit checks'

  - script: |
      pytest
    displayName: 'Run pytest'
