trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -e .[ci]
    displayName: 'Install CI dependencies'

  - script: |
      pre-commit install-hooks
    displayName: 'Install pre-commit hooks'

  - script: |
      pre-commit run --all-files
    displayName: 'Run pre-commit hooks'

  - script: |
      pytest
    displayName: 'Run pytest'
