trigger:
  - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    python-version: ['3.9', '3.11']

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python-version)'
      addToPath: true
    displayName: 'Set up Python $(python-version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -e .[ci]
    displayName: 'Install Python dependencies'

  - script: |
      pre-commit run --all-files
    displayName: 'Analyze all pre-commit checks'

  - script: |
      pytest
    displayName: 'Run pytest'
