name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run black
        run: black --check .

      - name: Run ruff
        run: ruff check .

      - name: Run isort
        run: isort --check-only .

      - name: Run yamllint
        run: yamllint -c yamllint.yaml .

      - name: Run markdownlint
        run: markdownlint -c markdownlint.yml **/*.md

      - name: Run pytest
        run: pytest
